using Npgsql;

using Dapper;

using System.Data;

using Microsoft.Extensions.Configuration;

using App.Database.Models;

namespace App.Database {
	public class DatabaseException : Exception {
		public DatabaseException() : base() { }
		public DatabaseException(string message) : base(message) { }
		public DatabaseException(string message, Exception innerException)
			: base(message, innerException) { }
	}

	public static class Database {
		private static string connectionString = "";
		internal static NpgsqlConnection Connection {
			get {
				NpgsqlConnection connection = new(connectionString);
				connection.Open();
				return connection;
			}
		}

		public static void Connect(string connectionString) {
			DefaultTypeMap.MatchNamesWithUnderscores = true;
			Database.connectionString = connectionString;

			try {
				using var connection = Connection;

				connection.Execute(@"
					CREATE TABLE IF NOT EXISTS categories (
						id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						name VARCHAR(50) NOT NULL
					);

					CREATE TABLE IF NOT EXISTS users (
						id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						login VARCHAR(50) NOT NULL UNIQUE,
						password VARCHAR(512) NOT NULL,
						name VARCHAR(50),
						role VARCHAR(16) NOT NULL
					);

					CREATE TABLE IF NOT EXISTS products (
						id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						name VARCHAR(100) NOT NULL,
						count INT NOT NULL,
						price INT NOT NULL,
						unit VARCHAR(50),
						image BYTEA,
						description VARCHAR(1000),
						discount REAL,
						provider VARCHAR(50),
						manufacturer VARCHAR(50)
					);

					CREATE TABLE IF NOT EXISTS product_categories (
						id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						product_id INT NOT NULL,
						category_id INT NOT NULL,
						CONSTRAINT product_id_fk FOREIGN KEY (product_id) REFERENCES products(id)
							ON DELETE CASCADE ON UPDATE CASCADE,
						CONSTRAINT category_id_fk FOREIGN KEY (category_id) REFERENCES categories(id)
							ON DELETE CASCADE ON UPDATE CASCADE
					);

					CREATE TABLE IF NOT EXISTS orders (
						id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						user_id INT NOT NULL,
						CONSTRAINT user_id_fk FOREIGN KEY (user_id) REFERENCES users(id)
							ON DELETE RESTRICT ON UPDATE RESTRICT
					);

					CREATE TABLE IF NOT EXISTS order_products (
						id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						order_id INT NOT NULL,
						product_id INT NOT NULL,
						count INT NOT NULL,
						CONSTRAINT order_id_fk FOREIGN KEY (order_id) REFERENCES orders(id)
							ON DELETE CASCADE ON UPDATE CASCADE,
						CONSTRAINT product_id_fk FOREIGN KEY (product_id) REFERENCES products(id)
							ON DELETE RESTRICT ON UPDATE RESTRICT
					);
				");

				try {
					Users.New("admin", "admin", Role.Admin);
				} catch { }
			} catch (PostgresException) { throw new DatabaseException("Не удалось инициализировать базу данных."); } catch (NpgsqlException) { throw new DatabaseException("Не удалось подключиться к базе данных."); }
		}
	}
}